# Generated by Django 3.2.11 on 2022-01-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('tg_username', models.CharField(max_length=100, unique=True, verbose_name='ник в Telegram')),
                ('discord_username', models.CharField(max_length=100, unique=True, verbose_name='ник в Discord')),
                ('bot_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='текущее состояния бота')),
            ],
            options={
                'verbose_name': ('продукт-менеджер',),
                'verbose_name_plural': 'продукт-менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание проекта')),
            ],
            options={
                'verbose_name': ('проект',),
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название уровня')),
            ],
            options={
                'verbose_name': ('уровень',),
                'verbose_name_plural': 'уровни',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval', models.TimeField(verbose_name='промежуток времени')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_times', to='telegram_bot.productmanager', verbose_name='продукт-менеджер')),
            ],
            options={
                'verbose_name': ('промежуток времени',),
                'verbose_name_plural': 'промежутки времени',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название команды')),
                ('product_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='telegram_bot.productmanager', verbose_name='продукт-менеджер')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='telegram_bot.project', verbose_name='проект')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='telegram_bot.time', verbose_name='временной интервал')),
            ],
            options={
                'verbose_name': ('команда',),
                'verbose_name_plural': 'команды',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('tg_username', models.CharField(max_length=100, unique=True, verbose_name='ник в Telegram')),
                ('discord_username', models.CharField(max_length=100, unique=True, verbose_name='ник в Discord')),
                ('bot_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='текущее состояния бота')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='telegram_bot.studentlevel', verbose_name='уровень ученика')),
            ],
            options={
                'verbose_name': ('ученик',),
                'verbose_name_plural': 'ученики',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='telegram_bot.project', verbose_name='проект')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='telegram_bot.student', verbose_name='ученик')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='telegram_bot.team', verbose_name='команда')),
                ('times', models.ManyToManyField(related_name='participants', to='telegram_bot.Time', verbose_name='выбранное время')),
            ],
            options={
                'verbose_name': ('участник',),
                'verbose_name_plural': 'участники',
            },
        ),
    ]
