# Generated by Django 3.2.11 on 2022-01-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='product_manager',
        ),
    ]
