# Generated by Django 3.2.11 on 2022-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_remove_team_product_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('pm__name', 'time_interval'), 'verbose_name': ('промежуток времени',), 'verbose_name_plural': 'промежутки времени'},
        ),
        migrations.AlterField(
            model_name='time',
            name='time_interval',
            field=models.TimeField(verbose_name='начало промежутка времени'),
        ),
    ]
