# Generated by Django 3.2.11 on 2022-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20220127_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanager',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chat ID в Telegram'),
        ),
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chat ID в Telegram'),
        ),
    ]
