# Generated by Django 3.2.11 on 2022-01-29 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20220127_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 11, 26, 19, 783685, tzinfo=utc), verbose_name='Дата начала проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на задание'),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 11, 26, 22, 942810, tzinfo=utc), verbose_name='Дата начала проекта'),
            preserve_default=False,
        ),
    ]
