# Generated by Django 3.2.11 on 2022-01-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_merge_0004_auto_20220128_1441_0004_auto_20220129_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('time__pm__name', 'time__time_interval'), 'verbose_name': ('команда',), 'verbose_name_plural': 'команды'},
        ),
    ]
