# Generated by Django 3.2 on 2022-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='trello_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на Trello-доску'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateTimeField(verbose_name='Дата окончания проекта'),
        ),
    ]
