# Generated by Django 3.2.11 on 2022-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_auto_20220130_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID рабочего пространства Trello'),
        ),
    ]
