# Generated by Django 4.0.1 on 2022-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_project_workspace_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'участники'},
        ),
        migrations.AlterModelOptions(
            name='productmanager',
            options={'verbose_name': 'продукт-менеджер', 'verbose_name_plural': 'продукт-менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'ученик', 'verbose_name_plural': 'ученики'},
        ),
        migrations.AlterModelOptions(
            name='studentlevel',
            options={'verbose_name': 'уровень', 'verbose_name_plural': 'уровни'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('time__pm__name', 'time__time_interval'), 'verbose_name': 'команда', 'verbose_name_plural': 'команды'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('pm__name', 'time_interval'), 'verbose_name': 'промежуток времени', 'verbose_name_plural': 'промежутки времени'},
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='имя'),
        ),
    ]
